### ISSUE TITLE
Feature - Add device name lookp functionality 

### ISSUE THREAD

**Issue by manish-modha** [scadaguru/syslog_unifi#1]
Very helpful application Thank you very much.  It will be nice if the application allows the following functionality. 

1. Device name lookup from CSV file
2. Add new word in notification when device connect first time 
3. Allow user format notification text
4. 	{MAC}
        {IP}
	{NAME}

**Comment by scadaguru** [comment]
Thanks for the feedback! @manish-modha 
There is a new build/image #v0.6 available linked below which addresses the first two requested items: CSV lookup for device name and preappends "(New)" if the device is seen first time. Enjoy!
https://github.com/scadaguru/syslog_unifi/releases/tag/v0.6

You will have to pull the latest image and rebuild your container to get these two features!

**Comment by scadaguru** [comment]
There is one more update **v0.7** to include item 3 and 4 from your feature request!
Here are the notes from this release, you will have to update your existing config.yaml as mentioned below!
Link to release notes: https://github.com/scadaguru/syslog_unifi/releases/tag/v0.7

Added feature to filter notifications like first time connect or IP changed etc!
Also now user can specify the notification text using any of these standard variables {NAME}, {IP}, {MAC}, {COUNT}.
You will need to update your config.yaml file to include these two items below under notifications section to utilize these new feature!

```
notifications:
    notification_string: "Device got connected Name: {NAME}, IP: {IP}, MAC: {MAC}, Count: {COUNT}" # Use any of these variables {NAME}, {IP}, {MAC}, {COUNT}
    default_notify_type: 6 # default:6, 1=Do not notify, 2=Notify only first time connect, 3=Notify only first time connect or IP changed, 4=always notify, 5=always notify till max count, 6=always notify till max count and then intermittent
   ```
